name: 'check_pr_for_labels'
description: 'Check PR for specific labels.  Fail if not found.'
inputs:
  required_labels:
    description: 'Comma separated list of required labels'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: "Checking PR for Labels ${{input.required_labels}}"
      env:
        REQUIRED_LABELS: ${{input.required_labels}}
      run: |
        ID=$(jq '.pull_request.name' $GITHUB_EVENT_PATH)
        LABELS=$( gh api /repos/asterisk/asterisk-gh-test/pulls/${PR} --jq '.labels[].name')
        echo "::notice::Labels required: $REQUIRED_LABELS"
        echo "::notice::Labels on PR: $LABELS"
        rc=0
        IFS=$','
        for rl in $REQUIRED_LABELS ; do
          has_it=0
          for l in $LABELS ; do
            [[ $l =~ $rl ]] && has_type+=1
          done
          if [ $has_type -eq 0 ] ; then
            echo "::error::At least 1 label must batch '$rl'"
            rc = 1
        done
        if [ $rc -eq 0 ] ; then
          echo "::notice::The PR has good labels"
        fi
        exit $rc
