name: CallableTest
run-name: ${{ github.actor }} has triggered a test of somethjing
on:
  workflow_call:
#  pull_request:
#    types: [opened, reopened]
env:
  UNITTEST_COMMAND: "test execute category /main/json/"

jobs:
  CT:
    runs-on: ubuntu-latest
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main

      - name: Checkout Asterisk
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          clean: true
          fetch-depth: 1
          set-safe-directory: true

      - name: Test echo
        run: |
          echo "Base callabvleTest"
          ls -al ./.github/scripts/
          ./.github/scripts/noop.sh
          exit 0
          