name: CallableTest
run-name: ${{ github.actor }} has triggered a test of somethjing
on:
  workflow_call:
#  pull_request:
#    types: [opened, reopened]
env:
  UNITTEST_COMMAND: "test execute category /main/json/"

jobs:
  CT:
    runs-on: ubuntu-latest
    steps:
      - name: Test echo
        run: |
          echo "MY callabvleTest"
          ls -al ./.github/scripts/
          ./.github/scripts/noop.sh
          exit 0
          
