name: NightlyAdmin
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  CloseStaleIssues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: asterisk/asterisk-ci-actions/.github/workflows/CloseStaleIssuesAndPRs.yml@main-close-stale
