name: PRChanged
run-name: "PR ${{ github.event.number }} Changed by ${{ github.actor }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  PRChanged:
    name: "run-check"
    concurrency:
      group: check-${{ github.base_ref }}-${{ github.ref_name }}
      cancel-in-progress: true
    uses: asterisk/asterisk-ci-actions/.github/workflows/AsteriskPRChanged.yml@main-pr-target
