name: PRReCheck
run-name: "PR ${{ github.event.number }} ${{ github.workflow }} by ${{ github.actor }}"
on:
  pull_request_target:
    types: [ labeled ]

jobs:
  PRReCheck:
    if: ${{ github.event.label.name == vars.RECHECKPR_LABEL }}
    concurrency:
      group: recheck-${{ github.base_ref }}-${{ github.ref_name }}
      cancel-in-progress: true
    name: "run-recheck"
    uses: asterisk/asterisk-ci-actions/.github/workflows/AsteriskPRReCheck.yml@main-pr-target
