name: PRReCheck
run-name: "PR ${{ github.event.number }} ${{ github.workflow }} by ${{ github.actor }}"
on:
  pull_request_target:
    types: [ labeled ]

concurrency:
  group: ${{ github.event.label.name }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  PRReCheck:
    if: ${{ github.event.label.name == vars.RECHECKPR_LABEL }}
    name: "run"
    uses: asterisk/asterisk-ci-actions/.github/workflows/AsteriskPRReCheck.yml@main
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
