name: PRMerged
run-name: "PR ${{github.event.number}} ${{github.event.action}} by ${{ github.actor }}"
on:
#  workflow_dispatch:
  pull_request_target:
    types: [closed]

concurrency:
  group: ${{github.workflow}}-${{github.event.number}}
  cancel-in-progress: true

env:
  ASTERISK_REPO:     ${{github.repository}}
  PR_NUMBER:         ${{github.event.number}}
  PR_COMMIT:         ${{github.event.pull_request.head.sha}}
  BRANCH:            ${{github.event.pull_request.base.ref}}
  GITHUB_TOKEN:      ${{secrets.GITHUB_TOKEN}}
  MODULES_BLACKLIST: ${{ vars.GATETEST_MODULES_BLACKLIST }} ${{ vars.UNITTEST_MODULES_BLACKLIST }}

jobs:
  CloseIssues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-close-fixed-issues@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  IdentifyBranches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get cherry-pick branches
        uses: asterisk/asterisk-ci-actions/GetCherryPickBranchesFromPR@main
        id: getbranches
        with:
          repo:         ${{env.ASTERISK_REPO}}
          pr_number:    ${{env.PR_NUMBER}}
          github_token: ${{env.GITHUB_TOKEN}}

  MergeCherryPicks:
    needs: [ IdentifyBranches ]
    if: needs.IdentifyBranches.outputs.branch_count > 0
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        branch: ${{ fromJSON(needs.IdentifyBranches.outputs.branches) }}
    runs-on: ubuntu-latest
    steps:
      - name: Cherry Pick PR ${{github.event.number}} to branch ${{matrix.branch}}
        uses: asterisk/asterisk-ci-actions/GetRepo@main
        with:
          repo:              ${{env.ASTERISK_REPO}}
          pr_number:         ${{env.PR_NUMBER}}
          base_branch:       ${{matrix.branch}}
          is_cherry_pick:    true
          build_script:      buildAsterisk.sh
          modules_blacklist: ${{env.MODULES_BLACKLIST}}
          github_token:      ${{env.GITHUB_TOKEN}}

      - name: Push Cherry Pick PR ${{github.event.number}} to branch ${{matrix.branch}}
        run: |
          echo "Need to do the git push here"
