name: PRReviewed
run-name: "PR ${{github.event.pull_request.number}} : Reviewed by ${{ github.actor }}"
on:
  pull_request_review:
    types: [submitted]

jobs:
  PRReview:
    if: github.event.review.author_association == 'MEMBER' 
#    if: github.event.review.state == 'approved' && github.event.review.author_association == 'MEMBER' 
    runs-on: ubuntu-latest
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main

      - name: Get cherry-pick branches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{github.event.pull_request.number}}
          CHERRY_PICK_REGEX: ${{ vars.CHERRY_PICK_REGEX }}
        run: |
          PICKS=$(gh api /repos/${REPO}/issues/${PR_NUMBER}/comments \
            --jq '.[].body | select(test("${{ vars.CHERRY_PICK_REGEX }}"))')
          IFS=$'\n'
          for pick in $PICKS ; do
            echo "Will cherry-pick to branch ${p##* }"
          done
