name: PRSubmitTestsTriggered
run-name: "PRSubmitTestsTriggered ${{github.event.number}} ${{github.event.action}} by ${{ github.actor }}"
on:
  workflow_run:
    workflows: [PRSubmitTests]
    types:
      - requested

jobs:
  PROpenUpdateUnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Set Labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --repo ${{github.repository}} \
            --remove-label ${{vars.TEST_CHECKS_PASSED_LABEL}} \
            --remove-label ${{vars.TEST_CHECKS_FAILED_LABEL}} \
            --remove-label ${{vars.TEST_GATES_PASSED_LABEL}} \
            --remove-label ${{vars.TEST_GATES_FAILED_LABEL}} \
            --remove-label ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}} \
            --remove-label ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}} \
            --remove-label ${{vars.CHERRY_PICK_GATES_PASSED_LABEL}} \
            --remove-label ${{vars.CHERRY_PICK_GATES_FAILED_LABEL}} \
            --remove-label ${{vars.PR_ACCEPTANCE_TEST_LABEL}} \
            --add-label ${{vars.TESTING_IN_PROGRESS}} \
            ${{env.PR_NUMBER}} || :

