name: Process Pull Request Test
run-name: ${{ github.actor }} is doing a test pull request
on:
#  workflow_dispatch:
#  issue_comment
  pull_request:
    types: [opened, reopened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_APP_TOKEN }}

jobs:
  AsteriskUnitTestsTest:
#    if: (github.event.issue.pull_request && startsWith(github.event.comment.body, 'recheck'))
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/t8c9l3c7/asteriskci-agent-rocky8:latest
      volumes:
        - /srv/cache/unittests:/usr/src/asterisk/asterisk-gh-test/asterisk

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          organization: asterisk
          application_id: ${{ secrets.ASTERISK_ORG_ACCESS_APP_ID }}
          application_private_key: ${{ secrets.ASTERISK_ORG_ACCESS_APP_PRIV_KEY }}
    
      - name: Setup for local ACT
        if: ${{ env.ACT }}
        run: |
          if [ -z "${ASTERISK_CI_URL}" ] || [ -z "${ASTERISK_URL}" ] ; then
            echo "::error::ASTERISK_CI_URL and ASTERISK_URL must be set in the environment"
            exit 1
          fi
          echo "::notice::Setting ASTERISK_CI_URL and ASTERISK_URL from environment"
          echo "PWD: $PWD"
          mount

      - name: Checkout Asterisk
        uses: actions/checkout@v3
        with:
          path: 'asterisk'
          # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
          # Default: true
          clean: true
          fetch-depth: 1
          # Add repository path as safe.directory for Git global config by running `git
          # config --global --add safe.directory <path>`
          # Default: true
          set-safe-directory: true

      - name: Write xml
        run: |
          cat >asterisk/unittests-results.xml <<-EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <testsuites>
            	<testsuite errors="0" time="0.96" tests="691" name="AsteriskUnitTests">
            		<properties>
            			<property name="version" value="GIT-master-78094346acM"/>
            		</properties>
            		<testcase time="0.0" classname="main.json" name="cep"/>
            		<testcase time="0.0" classname="main.json" name="type_timeval"/>
            		<testcase time="0.0" classname="main.json" name="name_number"/>
            	</testsuite>
            </testsuites>
          EOF
          echo "::group::github_trigger_event"
          echo '${{ toJSON(github.event) }}' > asterisk/event.json
          echo "::endgroup::"
          echo "::group::env"
          echo '${{ toJSON(env) }}' > asterisk/env.json
          echo "::endgroup::"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Asterisk Unit Tests Report
          working-directory: asterisk
          path: ./unittests-results.xml
          reporter: java-junit
          token: ${{ secrets.GITHUB_APP_TOKEN }}
