name: Pull Request Opened
run-name: ${{ github.actor }} has submitted a pull request
on:
#  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  SimpleChecks:
    runs-on: ubuntu-latest
#    container:
#      image: public.ecr.aws/t8c9l3c7/asteriskci-agent-rocky8:latest
    steps:
      - name: Install needed progs
        run: |
          sudo apt-get install jq -y

      - name: Check for labels
        uses: ./.github/actions/check_pr_for_labels
        with:
          required_labels: "(bug|enhancement|documentation),cherry-pick-.*"
#      - name: Check for issue
#        env:
#          BODY: ${{ toJSON(github.event.pull_request.body) }}
#        run: |
#          echo "BODY: $BODY"
#          msg=$(echo "$BODY" | sed -n -r -e "s/(Closes|Resolves):\s+#([0-9]+)/::notice::The PR \1 issue \2/gp")
#          if [ -n "$msg" ] ; then
#            echo "$msg"
#            has_issue=1
#            rc=0
#          else
#          	echo "::error::The PR does not have an issue associated with it"
#            has_issue=0
#            rc=1
#          fi
#          exit $rc
#
#  UnitTests:
#    needs: SimpleChecks
#    uses: ./.github/workflows/run_unit_tests.yml
