name: Test Workflow
run-name: "Test workflow started by ${{ github.actor }}"
on:
  workflow_dispatch:

env:
  CACHE_KEY: RUN:${{ github.run_number }}-RID:${{ github.run_id }}
   
jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ASTERISK_ORG_ACCESS_APP_ID }}
          application_private_key: ${{ secrets.ASTERISK_ORG_ACCESS_APP_PRIV_KEY }}
          organization: asterisk

      - name: Add Reviewers
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          PR_NUMBER: 46
          REVIEWERS: ${{ vars.PR_REVIEWERS }}
        run: |
          IFS=$'; \n'
          for r in $REVIEWERS ; do
            gh pr -R asterisk/asterisk-gh-test edit $PR_NUMBER --add-reviewer $r
          done
