name: Test Workflow
run-name: "Test workflow started by ${{ github.actor }}"
on:
  workflow_dispatch:
  
env:
  CACHE_KEY: PR:123-RUN:456-RID:101112
  
jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
        
      - name: GetAsterisk
        uses: asterisk/asterisk-ci-actions/GetAsterisk@main
        with:
          to-cache-key: ${{env.CACHE_KEY}}
          base-branch: master
          modules-blacklist: codec_ilbc test_crypto
          
  UseCachedResults:
    needs: TestWorkflow
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main

      - name: GetAsterisk
        uses: asterisk/asterisk-ci-actions/GetAsterisk@main
        with:
          from-cache-key: ${{env.CACHE_KEY}}
          base-branch: master
          modules-blacklist: codec_ilbc test_crypto

      - name: Run Gate Tests for branch master
        uses: asterisk/asterisk-ci-actions/RunAsteriskGateTests@main
        with:
          asterisk-repo:     ${{env.ASTERISK_REPO}}
          base-branch:       master
          github-token:      ${{secrets.GITHUB_TOKEN}}
          testsuite-repo:    ${{vars.TESTSUITE_REPO}}
          gatetest-group:    channels
          gatetest-commands: ${{vars.GATETEST_COMMANDS}} 

  DeleteCache:
    runs-on: ubuntu-latest
    needs: UseCachedResults
    if: ${{success()}}
    steps:
      - name: DeleteCache
        uses: snnaplab/delete-branch-cache-action@v1
        with:
          ref: refs/heads/master
          key: ${{env.CACHE_KEY}}
