name: Test Workflow
run-name: "Test workflow started by ${{ github.actor }}"
on:
  workflow_dispatch:

env:
  CACHE_KEY: RUN:${{ github.run_number }}-RID:${{ github.run_id }}
   
jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.ASTERISK_ORG_ACCESS_APP_CLIENT_SECRET }}
          GITHUB_TOKEN: ${{ secrets.ASTERISK_ORG_ACCESS_APP_CLIENT_SECRET }}
          PR_NUMBER: 46
          REVIEWERS: ${{ vars.PR_REVIEWERS }}
        run: |
          IFS=$'; \n'
          for r in $REVIEWERS ; do
            gh pr edit $PR_NUMBER --add-reviewer $r
          done
