name: Test Workflow
run-name: "Test workflow started by ${{ github.actor }}"
on:
  workflow_dispatch:

env:
  CACHE_KEY: RUN:${{ github.run_number }}-RID:${{ github.run_id }}
   
jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Asterisk
      uses: asterisk/asterisk-ci-actions/checkout@main
      with:
        ref: master
        clean: true
        fetch-depth: 5
        set-safe-directory: true
        quiet: true

    - name: Cache Build Products
      if: ${{ env.CACHE_KEY }} != ""
      uses: actions/cache@v3
      with:
        key: ${{ env.CACHE_KEY }}
        path: ./tests/CI
