name: Test Workflow
run-name: "Test workflow started by ${{ github.actor }}"
on:
  workflow_dispatch:
  
env:
  CACHE_KEY: PR:123-RUN:456-RID:789
  
jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
        
      - name: GetAsterisk
        uses: asterisk/asterisk-ci-actions/GetAsterisk@main
        with:
          to-cache-key: ${{env.CACHE_KEY}}
          base-branch: master
          modules-blacklist: codec_ilbc test_crypto
          
  UseCachedResults:
    needs: TestWorkflow
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main

      - name: GetAsterisk
        uses: asterisk/asterisk-ci-actions/GetAsterisk@main
        with:
          from-cache-key: ${{env.CACHE_KEY}}
          base-branch: master
          modules-blacklist: codec_ilbc test_crypto

      - name: RunUnitTests
        uses: asterisk/asterisk-ci-actions/RunAsteriskUnitTests@main
        with:
          base-branch: master

  DeleteCache:
    runs-on: ubuntu-latest
    needs: UseCachedResults
    if: ${{success()}}
    steps:
      - name: DeleteCache
        uses: snnaplab/delete-branch-cache-action@v1
        with:
          ref: refs/heads/master
          key: ${{env.CACHE_KEY}}
